name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - name: Install dependencies (if any)
        run: |
          pip install --upgrade pip
          # pip install -r requirements.txt  # Uncomment if you add requirements

      - name: Run self-check / dry run
        run: |
          python log_clusterer.py --input demo --out test_report.html --sanitize --export-registry test_registry.json

      # Optionally, add linting or tests here
      # - name: Lint with flake8
      #   run: |
      #     pip install flake8
      #     flake8 .
